version: '3'
services:
  request-handler:
    build: .
    container_name: request-handler
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      POSTGRES_PRISMA_URL: "${POSTGRES_PRISMA_URL}"
      POSTGRES_URL_NON_POOLING: "${POSTGRES_URL_NON_POOLING}"
      UPSTASH_REDIS_URL: "${UPSTASH_REDIS_URL}"
      UPSTASH_REDIS_TOKEN: "${UPSTASH_REDIS_TOKEN}"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - request-handler
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/letsencrypt # Map your Let's Encrypt certificates
      - ./challenge:/var/www/html # Map the challenge directory
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
